version: 2
jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run:
          name: Install APT packages
          command: |
            apt-get update -y
            apt-get install jq zip -y
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install NPM dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test
      - run:
          name: Pack
          command: bash .circleci/pack.sh
      - store_artifacts:
          path: ~/repo/public
      - store_artifacts:
          path: ~/repo/build

  build-test-and-deploy:
    working_directory: ~/repo
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run:
          name: Install APT packages
          command: |
            apt-get update -y
            apt-get install jq zip -y
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-
      - run:
          name: Install NPM dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test
      - run:
          name: Pack
          command: bash .circleci/pack.sh
      - store_artifacts:
          path: ~/repo/public
      - store_artifacts:
          path: ~/repo/build
      - deploy:
          name: Deploy
          command: bash .circleci/deploy-to-netlify.sh

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            tags:
              ignore: /^v.*/
  build-test-and-deploy:
    jobs:
      - build-test-and-deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
