version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install NPM dependencies
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: npm run build
      - store_artifacts:
          path: ~/repo/build

workflows:
  version: 2
  build:
    jobs:
      - build
